name:                lambda-ski
version:             0.1.0.0
github:              "githubuser/lambda-ski"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

tested-with:   GHC == 8.10.7
             , GHC == 9.0.2
             , GHC == 9.2.1

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lambda-ski#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

executables:
  lambda-ski-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-ski

  benchmark:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-ski
      - criterion


tests:
  lambda-ski-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-ski
    - hspec
    - QuickCheck
    - quickcheck-io
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover

