name: Haskell-CI
on:
  - push
  - pull_request
jobs:
  build:
    name: GHC ${{ matrix.ghc-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc-version: '9.2.8'
            allow-failure: false
          - ghc-version: '9.4.8'
            allow-failure: false
          - ghc-version: '9.6.6'
            allow-failure: false
          - ghc-version: '9.8.2'
            allow-failure: false
          - ghc-version: '9.8.4'
            allow-failure: false
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: 'latest'

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build --dry-run
        # The dry-run writes dist-newstyle/cache/plan.json used for cache key.

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}-

      - name: Install dependencies
        run: cabal build all --only-dependencies

      - name: Save cached dependencies
        uses: actions/cache/save@v4
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all --test-show-details=direct

